name: Build Gradle & Deploy Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run tests
        run: ./gradlew test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t fsngpz/usc-engine-image:latest .

      - name: Push Docker image to registry
        run: docker push fsngpz/usc-engine-image:latest

  deploy:
    name: Deploy to dev
    needs: build
    runs-on: [ usc-ec2 ]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull fsngpz/usc-engine-image:latest
      - name: Delete previous docker container
        run: sudo docker rm -f usc-engine
      - name: Run docker container
        run: sudo docker run -d -p 9090:9090 --name usc-engine fsngpz/usc-engine-image:latest -e SPRING_PROFILES_ACTIVE=dev
